import { type NextPage } from "next";
import Head from "next/head";

import { Swiper, SwiperSlide } from "swiper/react";
import { Mousewheel, Pagination } from "swiper";

import { PresentationSlide } from "~/components/PresentationSlide";
import { GlassdoorSlide } from "~/components/GlassdoorSlide";
import { ObjectivesSlide } from "~/components/ObjectivesSlide";
import { EndingSection } from "~/components/EndingSection";
import { ExperienceSlide } from "~/components/ExperienceSlide";
import { ContributionSlide } from "~/components/ContributionSlide";

import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import { useEnterprise } from "~/context/EnterpriseContext";

const contributionSlideData = {
  firstParagraph:
    "Tenho conhecimento consolidado em desenvolvimento web com React, criando e integrando apis e seguindo boas práticas de desenvolvimento.",
  secondParagraph:
    "Acredito que posso agregar muito nesse estilo de trabalho da 77Sol, pois sou muito proativo e possuo fácil adaptabilidade em diversas situações, tendo em vista que já foi exigido de mim na minhaexperiência profissional. Com isso, acredito que posso contribuir emuito com a criação e consolidação de processos, e de entregas comênfase em qualidade.",
};

const objectivesSlideData = [
  "Meu objetivo no mundo da tecnologia é trabalhar em um local onde posso atuar criando soluções tecnológicas enquanto aprecio o processo.",
  "",
  "Além disso, meu objetivo no dia a dia é crescer como profissional,sendo referência técnica na empresa e ajudando a equipe a crescer junto comigo.",
];

const Home: NextPage = () => {
  const { enterpriseName } = useEnterprise();

  return (
    <>
      <Head>
        <title>{enterpriseName} | Gustavo Gava</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="relative h-screen max-h-screen overflow-hidden bg-slate-800">
        <Swiper
          direction="vertical"
          pagination={{
            type: "progressbar",
          }}
          draggable={false}
          preventClicks={false}
          modules={[Mousewheel, Pagination]}
          mousewheel
        >
          <SwiperSlide>
            <PresentationSlide />
          </SwiperSlide>

          <SwiperSlide>
            <ExperienceSlide />
          </SwiperSlide>

          {/* <SwiperSlide>
            <GlassdoorSlide />
          </SwiperSlide> */}

          <SwiperSlide>
            <ObjectivesSlide paragraphs={objectivesSlideData} />
          </SwiperSlide>

          <SwiperSlide>
            <ContributionSlide {...contributionSlideData} />
          </SwiperSlide>

          <SwiperSlide>
            <EndingSection />
          </SwiperSlide>
        </Swiper>
      </main>
    </>
  );
};

export default Home;
