import { type NextPage } from "next";
import Head from "next/head";

import { Swiper, SwiperSlide } from "swiper/react";
import { EffectCreative, Mousewheel, Pagination } from "swiper";

import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import Image from "next/image";
import { ScrollDownMouseAnimated } from "~/components/ScrollDownMouseAnimated";
import { TextHighlighted } from "~/components/TextHighlighted";
import { PresentationSlide } from "~/components/PresentationSlide";
import { GlassdoorSlide } from "~/components/GlassdoorSlide";

import ChevronLeft from "../../public/chevron-left.svg";
import { ExperienceSlide } from "~/components/ExperienceSlide";

const contentArray = [
  {
    title: "Slide 1",
    image: {
      url: "https://wallpapercave.com/wp/IhDuV8R.jpg",
      alt: "sunset",
    },
  },
  {
    title: "Slide 2",
    image: {
      url: "/datum_glassdoor_laptop.png",
      alt: "sunset",
    },
  },
  {
    title: "Slide 3",
    image: {
      url: "https://wallpapercave.com/wp/IhDuV8R.jpg",
      alt: "sunset",
    },
  },
  {
    title: "Slide 4",
    image: {
      url: "https://wallpapercave.com/wp/IhDuV8R.jpg",
      alt: "sunset",
    },
  },
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="max-h-screen overflow-hidden bg-white">
        <header className="flex w-full border-[1px] shadow-lg">
          <div className="m-auto flex w-full max-w-5xl items-center justify-between p-2">
            <a className="logo">Datum</a>

            <span>Gustavo Gava</span>
          </div>
        </header>
      </div> */}

      <main className="relative h-screen max-h-screen overflow-hidden bg-slate-800">
        <Swiper
          direction="vertical"
          pagination={{
            type: "progressbar",
            clickable: true,
          }}
          modules={[Mousewheel, Pagination, EffectCreative]}
          effect={"creative"}
          creativeEffect={{
            prev: {
              translate: [0, "-100%", 0],
            },
            next: {
              translate: [0, "100%", 0],
            },
          }}
          mousewheel
        >
          <SwiperSlide>
            <PresentationSlide />
          </SwiperSlide>

          <SwiperSlide>
            <ExperienceSlide />
          </SwiperSlide>

          <SwiperSlide>
            <GlassdoorSlide />
          </SwiperSlide>

          <SwiperSlide>
            <div className="flex h-full items-center justify-center">
              <div>
                <h3>Quais são minhas expectativas?</h3>
              </div>
            </div>
          </SwiperSlide>

          <SwiperSlide>
            <div>Espero que você que tenha gostado do meu currículo!</div>

            <p>
              Caso não for o candidato ideal para a Datum, espero que tenha sido
              uma experiência diferente e agradável para você!
            </p>

            <div>
              E claro, estou totalmente a disposição para conversar e demonstrar
              o que posso acrescentar na empresa, ao mesmo tempo que conheço
              mais da cultura.
            </div>

            <div>
              <p>Meus contatos:</p>

              <ul>
                <li>email: gustavogavadev@gmail.com</li>
                <li>linkedin: @gustavogava</li>
              </ul>
            </div>
          </SwiperSlide>
        </Swiper>
      </main>
    </>
  );
};

export default Home;
